name: Trigger All Workflows in Another Repo

on:
  push:
    branches:
      - main

jobs:
  trigger-all-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        run: |
          echo "REPO=sreegithub19/codeforces_script" >> $GITHUB_ENV
          echo "TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "REF=ruby_" >> $GITHUB_ENV

      - name: Fetch all workflows
        id: get_workflows
        run: |
          workflows=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN" https://api.github.com/repos/$REPO/actions/workflows)
          echo "$workflows" > workflows.json
          echo "workflows=$(jq -r '.workflows[].path' workflows.json)" >> $GITHUB_ENV

      - name: Trigger each workflow
        run: |
          for workflow in $workflows; do
            echo "Triggering workflow $workflow"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $TOKEN" \
              https://api.github.com/repos/$REPO/actions/workflows/$workflow/dispatches \
              -d "{\"ref\":\"$REF\"}"
            sleep 60  # Adjust the wait time as needed
          done